apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2024-01-26T07:57:53Z","generation":2,"labels":{"app":"synergychat-api"},"name":"synergychat-api","namespace":"default","resourceVersion":"25829","uid":"68861cdb-fe75-463f-b7fd-d94165ca220e"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"synergychat-api"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"synergychat-api"}},"spec":{"containers":[{"env":[{"name":"API_PORT","valueFrom":{"configMapKeyRef":{"key":"API_PORT","name":"synergychat-api-configmap"}}}],"image":"lanecwagner/synergychat-api:latest","imagePullPolicy":"Always","name":"synergychat-api","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-01-26T08:20:17Z","lastUpdateTime":"2024-01-26T08:20:22Z","message":"ReplicaSet \"synergychat-api-78c77594dd\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-01-27T23:57:49Z","lastUpdateTime":"2024-01-27T23:57:49Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":2,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-01-26T07:57:53Z"
  generation: 3
  labels:
    app: synergychat-api
  name: synergychat-api
  namespace: default
  resourceVersion: "26568"
  uid: 68861cdb-fe75-463f-b7fd-d94165ca220e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: synergychat-api-configmap
        image: lanecwagner/synergychat-api:latest
        imagePullPolicy: Always
        name: synergychat-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-26T08:20:17Z"
    lastUpdateTime: "2024-01-26T08:20:22Z"
    message: ReplicaSet "synergychat-api-78c77594dd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-01-27T23:57:49Z"
    lastUpdateTime: "2024-01-27T23:57:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
